name: Issuer
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: rishabhgupta/git-action-issue@v2
        id: Issue
        with:
            token: ${{ secrets.ACTION_TOKEN }}
            title: $(date +'%Y-%m-%d') 주간 보고
            body: 댓글로 한 일 적어주세요~
            assignees: 'alertjjm'
