name: Issuer
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: rishabhgupta/git-action-issue@v2
        id: Issue
        with:
            token: ${{ secrets.ACTION_TOKEN }}
            title: Title
            body: body
            assignees: 'alertjjm'
      - run: |
          echo ${{ steps.issue.outputs.issue }}
